"""Create rain_forecasts table

Revision ID: 131ebf425a8b
Revises: edc7f627c4c8
Create Date: 2025-10-06 22:06:29.376672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131ebf425a8b'
down_revision = 'edc7f627c4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rain_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_time', sa.DateTime(), nullable=False),
    sa.Column('rain_mm', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rain_forecasts')
    # ### end Alembic commands ###
